services:
  - type: web
    name: di-stock-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 app:app
    envVars:
      - key: PORT
        value: 8000
